/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meinke;

import java.awt.Component;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author classic
 */
public class BlockPanel extends javax.swing.JPanel {

    private int BlockWidth = 100;
    private int BlockHeight = 100;
    private int BlockMinPadding = 10;
    
    private static final int AnimateTimerRateMS = 10;
    private static final int AnimateLengthMS = 500;
    
    private List<Point> OrigPoints = new ArrayList<>();
    private List<Point> DestPoints = new ArrayList<>();
    long startTimeMS = 0;
    
    
    private Timer timer = new Timer(AnimateTimerRateMS, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            timeraction();
        }
    });
    /**
     * Creates new form BlockPanel
     */
    public BlockPanel() {
        initComponents();
    }
    
    public static float  easeOut(float t,float b , float c, float d) {
		float s = 1.70158f;
		return c*((t=t/d-1)*t*((s+1)*t + s) + 1) + b;
    }
    
    private void timeraction(){
        long ctime = System.currentTimeMillis() - startTimeMS;
        
        for (int i = 0; i < this.getComponents().length; i++) {
            Component comp = this.getComponents()[i];
            int x = (int) easeOut(ctime, (float) OrigPoints.get(i).getX(), (float) DestPoints.get(i).getX() - (float) OrigPoints.get(i).getX(), AnimateLengthMS);
            int y = (int) easeOut(ctime, (float) OrigPoints.get(i).getY(), (float) DestPoints.get(i).getY() - (float) OrigPoints.get(i).getY(), AnimateLengthMS);
            comp.setLocation(x, y);
        }

        if (ctime > AnimateLengthMS) {
            timer.stop();
        }
        this.repaint();
    }

    private void reset(){
        timer.stop();
        
        int padding = 0;
        int columnCount=1;
        
        while ((columnCount * (BlockWidth + BlockMinPadding)) + BlockMinPadding < this.getWidth()) {            
            columnCount ++;
        }
        if (columnCount > 1) {
            columnCount--;
        }
        padding = (this.getWidth() - (columnCount * BlockWidth)) / (columnCount + 1);
        if (padding < BlockMinPadding) {
            padding = BlockMinPadding;
        }
        
        OrigPoints.clear();
        DestPoints.clear();
        int compnum = 0;
        for (Component comp : this.getComponents()) {
            int column = compnum % columnCount;
            int row = compnum / columnCount;
            OrigPoints.add(comp.getLocation());
            DestPoints.add(new Point((column * (BlockWidth + padding)) + padding, (row * (BlockHeight + padding)) + padding));
            
            comp.setSize(BlockWidth, BlockHeight);
            if(comp.getX() < 0 && comp.getY() < 0){
                comp.setLocation(DestPoints.get(DestPoints.size() - 1));
            }
            
            compnum++;
        }
        
        startTimeMS = System.currentTimeMillis();
        timer.setRepeats(true);
        timer.start();
    }

    public void addComponent(Component comp){
        timer.stop();
        this.add(comp);
        reset();
    }
    
    public void removeComponent(Component comp){
        timer.stop();
        this.remove(comp);
        reset();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        reset();
    }//GEN-LAST:event_formComponentResized

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
