/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meinke;

import java.awt.Color;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author classic
 */
public class SettingsForm extends javax.swing.JDialog {

    /**
     * Creates new form SettingsForm
     */
    public SettingsForm() {
        initComponents();
        jSliderSarcasm.setValue(Meinke.SARCASM_LEVEL);
        jTextFieldFrom.setText(Meinke.FROM_GPS_PATH);
        jTextFieldTo.setText(Meinke.TO_GPS_PATH);
        jSpinnerAge.setValue(Meinke.IGNORE_TRACKS_AFTER);
        jSpinnerLength.setValue(Meinke.TRIM_TRACKS_AFTER);
        jSliderSarcasmStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelFrom = new javax.swing.JLabel();
        jTextFieldFrom = new javax.swing.JTextField();
        jButtonFrom = new javax.swing.JButton();
        jLabelTo = new javax.swing.JLabel();
        jTextFieldTo = new javax.swing.JTextField();
        jButtonTo = new javax.swing.JButton();
        jSliderSarcasm = new javax.swing.JSlider();
        jLabelSarcasm = new javax.swing.JLabel();
        jLabelSarcasmValue = new javax.swing.JLabel();
        jLabelSarcasm1 = new javax.swing.JLabel();
        jLabelSarcasm2 = new javax.swing.JLabel();
        jSpinnerAge = new javax.swing.JSpinner();
        jSpinnerLength = new javax.swing.JSpinner();
        jLabelSarcasm3 = new javax.swing.JLabel();
        jLabelSarcasm4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Settings");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Import/Export Paths"), "Import/Export Paths"));

        jLabelFrom.setText("From GPS folder");

        jTextFieldFrom.setText("jTextField1");

        jButtonFrom.setText("...");
        jButtonFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFromActionPerformed(evt);
            }
        });

        jLabelTo.setText("To GPS folder");

        jTextFieldTo.setText("jTextField1");

        jButtonTo.setText("...");
        jButtonTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFrom)
                    .addComponent(jLabelTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFrom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFrom)
                    .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTo)
                    .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSliderSarcasm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSarcasmStateChanged(evt);
            }
        });

        jLabelSarcasm.setText("SARcasm Level");

        jLabelSarcasmValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSarcasmValue.setText("50%");

        jLabelSarcasm1.setText("Ignore tracks older than");

        jLabelSarcasm2.setText("Trim track jumps that greater than");
        jLabelSarcasm2.setEnabled(false);

        jSpinnerAge.setModel(new javax.swing.SpinnerNumberModel(2, 1, 365, 1));

        jSpinnerLength.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jSpinnerLength.setEnabled(false);

        jLabelSarcasm3.setText("miles");
        jLabelSarcasm3.setEnabled(false);

        jLabelSarcasm4.setText("days");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSarcasm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderSarcasm, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSarcasmValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSarcasm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSarcasm4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSarcasm2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerLength, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSarcasm3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSarcasm1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSarcasm4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSarcasm2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSarcasm3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSliderSarcasm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSarcasm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSarcasmValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderSarcasmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSarcasmStateChanged
        int val = jSliderSarcasm.getValue();
        int rval = 255;
        int gval = 255;
        if(val < 50){
            rval = (int)(((double)val / (double)50) * 255);
        }else if (val > 50){
            gval = 255 - (int)(((double)(val-50) / (double)50) * 255);
        }
        jLabelSarcasmValue.setForeground(new Color((int)(rval * 0.75), (int)(gval * 0.75), 0));
        jLabelSarcasmValue.setText(val + "%");
        
        if(val == 100){
            JOptionPane.showMessageDialog(this, Meinke.insults[new Random().nextInt(Meinke.insults.length)],"Duh.",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jSliderSarcasmStateChanged

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.hide();
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        Meinke.FROM_GPS_PATH = jTextFieldFrom.getText();
        Meinke.TO_GPS_PATH = jTextFieldTo.getText();
        Meinke.SARCASM_LEVEL = jSliderSarcasm.getValue();
        Meinke.IGNORE_TRACKS_AFTER = (Integer)jSpinnerAge.getValue();
        Meinke.TRIM_TRACKS_AFTER = (Integer)jSpinnerLength.getValue();
        Meinke.saveSettings();
        this.hide();
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFromActionPerformed
        String val = chooseFolder();
        if(val != null){
            jTextFieldFrom.setText(val);
        }
    }//GEN-LAST:event_jButtonFromActionPerformed

    private void jButtonToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToActionPerformed
        String val = chooseFolder();
        if (val != null) {
            jTextFieldTo.setText(val);
        }
    }//GEN-LAST:event_jButtonToActionPerformed

    private String chooseFolder() {
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int ret = jf.showOpenDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            return jf.getSelectedFile().getAbsolutePath();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonFrom;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonTo;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelSarcasm;
    private javax.swing.JLabel jLabelSarcasm1;
    private javax.swing.JLabel jLabelSarcasm2;
    private javax.swing.JLabel jLabelSarcasm3;
    private javax.swing.JLabel jLabelSarcasm4;
    private javax.swing.JLabel jLabelSarcasmValue;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSliderSarcasm;
    private javax.swing.JSpinner jSpinnerAge;
    private javax.swing.JSpinner jSpinnerLength;
    private javax.swing.JTextField jTextFieldFrom;
    private javax.swing.JTextField jTextFieldTo;
    // End of variables declaration//GEN-END:variables
}
